### ISSUE TITLE
Merge bot issue 

### ISSUE THREAD

**Issue by MrPrimeOfficialBots** [AbirHasan2005/VideoMerge-Bot#12]
@primemergebot

(https://primemergebot.herokuapp.com/)

Application Logs
2022-06-03T06:31:28.482356+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2022-06-03T06:31:29.096162+00:00 heroku[worker.1]: State changed from starting to up
2022-06-03T06:31:30.311276+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-03T06:31:30.311289+00:00 app[worker.1]:   File "/app/main.py", line 39, in <module>
2022-06-03T06:31:30.311365+00:00 app[worker.1]:     NubBot = Client(
2022-06-03T06:31:30.311367+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyromod/listen/listen.py", line 40, in __init__
2022-06-03T06:31:30.311446+00:00 app[worker.1]:     self.old__init__(*args, **kwargs)
2022-06-03T06:31:30.311463+00:00 app[worker.1]: TypeError: Client.__init__() got an unexpected keyword argument 'session_name'
2022-06-03T06:31:30.548308+00:00 heroku[worker.1]: Process exited with status 1
2022-06-03T06:31:30.614253+00:00 heroku[worker.1]: State changed from up to crashed

Please help me to resolve

**Comment by yashoswalyo** [comment]
downgrade pyrogram

**Comment by AbirHasan2005** [comment]
Fixed in 431c250eb55c61e8269801cf971201ce4afeb067
