### ISSUE TITLE
Bot not starting 

### ISSUE THREAD

**Issue by MrViralCollections** [AbirHasan2005/VideoMerge-Bot#13]
2022-06-15T16:27:17.359315+00:00 app[api]: Deploy by user mergebottg@gmail.com
2022-06-15T16:27:21.000000+00:00 app[api]: Build succeeded
2022-06-15T16:27:22.825444+00:00 app[api]: Scaled to worker@1:Free by user mergebottg@gmail.com
2022-06-15T16:27:27.175077+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2022-06-15T16:27:27.823562+00:00 heroku[worker.1]: State changed from starting to up
2022-06-15T16:27:31.864661+00:00 app[api]: Scaled to worker@0:Free by user mergebottg@gmail.com
2022-06-15T16:27:31.978128+00:00 heroku[worker.1]: State changed from up to down
2022-06-15T16:27:32.658766+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2022-06-15T16:27:33.240719+00:00 heroku[worker.1]: Process exited with status 143
2022-06-15T16:27:33.954702+00:00 app[api]: Scaled to worker@1:Free by user mergebottg@gmail.com
2022-06-15T16:27:38.762319+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2022-06-15T16:27:39.402722+00:00 heroku[worker.1]: State changed from starting to up
2022-06-15T16:28:06.802000+00:00 app[worker.1]: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")
2022-06-15T16:28:06.802019+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-15T16:28:06.802026+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
2022-06-15T16:28:06.802027+00:00 app[worker.1]:     return await self.storage.get_peer_by_id(peer_id)
2022-06-15T16:28:06.802027+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 147, in get_peer_by_id
2022-06-15T16:28:06.802027+00:00 app[worker.1]:     raise KeyError(f"ID not found: {peer_id}")
2022-06-15T16:28:06.802027+00:00 app[worker.1]: KeyError: 'ID not found: -1001292494548'
2022-06-15T16:28:06.802028+00:00 app[worker.1]: 
2022-06-15T16:28:06.806598+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-06-15T16:28:06.806598+00:00 app[worker.1]: 
2022-06-15T16:28:06.806599+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-15T16:28:06.806599+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-06-15T16:28:06.806599+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-06-15T16:28:06.806599+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
2022-06-15T16:28:06.806600+00:00 app[worker.1]:     await self.user_callback(client, message, *args)
2022-06-15T16:28:06.806600+00:00 app[worker.1]:   File "/app/main.py", line 49, in start_handler
2022-06-15T16:28:06.806600+00:00 app[worker.1]:     await AddUserToDatabase(bot, m)
2022-06-15T16:28:06.806600+00:00 app[worker.1]:   File "/app/helpers/database/add_user.py", line 13, in AddUserToDatabase
2022-06-15T16:28:06.806601+00:00 app[worker.1]:     await bot.send_message(
2022-06-15T16:28:06.806601+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/messages/send_message.py", line 130, in send_message
2022-06-15T16:28:06.806601+00:00 app[worker.1]:     peer=await self.resolve_peer(chat_id),
2022-06-15T16:28:06.806602+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 109, in resolve_peer
2022-06-15T16:28:06.806602+00:00 app[worker.1]:     await self.send(
2022-06-15T16:28:06.806602+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2022-06-15T16:28:06.806602+00:00 app[worker.1]:     r = await self.session.send(
2022-06-15T16:28:06.806602+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
2022-06-15T16:28:06.806603+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2022-06-15T16:28:06.806603+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
2022-06-15T16:28:06.806603+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-06-15T16:28:06.806603+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-06-15T16:28:06.806603+00:00 app[worker.1]:     raise getattr(
2022-06-15T16:28:06.806607+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")
 Autoscroll with output[Save](https://dashboard.heroku.com/apps/videomergerbot/logs#)
[Blogs](https://blog.heroku.com/)
[Careers](https://www.heroku.com/careers)
[Documentation](https://devcenter.heroku.com/)
[Support](https://help.heroku.com/)

**Comment by MrViralCollections** [comment]
Now it's working but my video is in streamtape how to upload in telegram please help me
